### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by devforcactus** [devforcactus/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by illiapavlov93** [comment]
Hey! I am a 3-year-old cactus who likes to stand on the table and listen to Vova Kushnir's mouse running. Sometimes it happens that they put me on a shelf with books, give me a supporting role. It is stressful to constantly play the main roles, so I do not mind, besides, you can read most likely smart books, but I'm not sure.

**Comment by illiapavlov93** [comment]
<h2>Résumé</h2>
<p>&mdash; Hey! I am a 3-year-old cactus who likes to stand on the table and listen to Vova Kushnir's mouse running. Sometimes it happens that they put me on a shelf with books, give me a supporting role. It is stressful to constantly play the main roles, so I do not mind, besides, you can read most likely smart books, but I'm not sure.</p>
