### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by devforcactus** [devforcactus/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by illiapavlov93** [comment]
Katniss the Cactus

	•	https://www.fb.com/KatnissCactus
	•	KatnissCactus@binary-studio.com
	•	https://twitter.com/rKatnissCactus
	•	https://www.instagram.com/KatnissCactus
