### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by devforcactus** [devforcactus/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by illiapavlov93** [comment]
LANGUAGES

🇺🇸 ENGLISH 🌵 ḓ̷̘͈̑̃͂͒ͅf̵̫̆̑d̶̦͓͓̰̅

SKILLS
Acting skills
Can be grown in almost all climates in the world
Ability to stand, stand a lot
Take all the negativity on myself
Can hurt if you hurt

CHARACTER

I don't like a lot of activities, I only agree to be moved from place to place sometimes. Vindictive: touch me and I touch you.
